IMPORTS="/home/tsel/data/today-imports"
SITEDB_RAW="/home/tsel/data/today-sitedb"
PUFILES_RAW="/home/tsel/data/today-pufiles"
PREPARED_DIR="/home/tsel/data/today-prepared"
PU_REG="/home/tsel/data/pu-reg"
TOOLS="/home/tsel/tools"